// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var DataTable = require("./components/DataTable.bs.js");
var ReactDOMRe = require("reason-react/lib/js/src/legacy/ReactDOMRe.js");

var props = {};

ReactDOMRe.renderToElementWithId(React.createElement(DataTable.make, props), "app");

/*  Not a pure module */
