// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Random = require("bs-platform/lib/js/random.js");

function DataTable(Props) {
  var data = $$Array.init(3000, (function (param) {
          return Random.$$int(3000);
        }));
  var match = React.useState(function () {
        return data;
      });
  return React.createElement("div", undefined, React.createElement("h3", undefined, "Data Go Here!"), React.createElement("div", undefined, React.createElement("table", undefined, React.createElement("tbody", undefined, $$Array.mapi((function (i, dataItem) {
                                return React.createElement("tr", {
                                            key: String(i)
                                          }, React.createElement("td", undefined, i), React.createElement("td", undefined, dataItem));
                              }), match[0])))));
}

var make = DataTable;

exports.make = make;
/* react Not a pure module */
