// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function fetchData(setDataList) {
  fetch("/api/data").then(function (res) {
            return res.json();
          }).then(function (dataJson) {
          console.error(dataJson);
          Curry._1(setDataList, (function (param) {
                  return dataJson;
                }));
          return Promise.resolve(undefined);
        }).catch(function (err) {
        console.error(err);
        return Promise.resolve(undefined);
      });
  
}

function DataList(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setDataList = match[1];
  return React.createElement("div", undefined, React.createElement("h3", undefined, "Data Go Here!"), React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (param) {
                          return fetchData(setDataList);
                        })
                    }, "Fetch")), React.createElement("div", undefined, React.createElement("ul", undefined, $$Array.mapi((function (i, dataItem) {
                            return React.createElement("li", {
                                        key: String(i)
                                      }, dataItem);
                          }), match[0]))));
}

var make = DataList;

exports.fetchData = fetchData;
exports.make = make;
/* react Not a pure module */
